-- +goose Up
INSERT INTO roles (id, label, description, is_system, enabled, created_at, created_by, updated_at)
VALUES
  ('__role_hrbp__', 'HRBP', '部门 HRBP，可管理部门范围内简历与通知', TRUE, TRUE, CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('__role_hrd__', 'HRD', 'HRD，可继承 HRBP、主管与锻炼干部权限', TRUE, TRUE, CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('__role_manager__', '主管', '业务主管，可参与简历解析和推荐', TRUE, TRUE, CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('__role_trainee__', '锻炼干部', '锻炼干部，可查看并参与基础解析', TRUE, TRUE, CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('__role_social_owner__', '社招负责人', '社招负责人，默认仅访问社招简历', TRUE, TRUE, CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('__role_campus_owner__', '校招负责人', '校招负责人，默认仅访问校招简历', TRUE, TRUE, CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP),
  ('__role_super_admin__', '超级管理员', '系统超级管理员，拥有全部初始白名单权限', TRUE, TRUE, CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP)
ON CONFLICT(id) DO UPDATE SET
  label = excluded.label,
  description = excluded.description,
  is_system = excluded.is_system,
  enabled = excluded.enabled,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO permissions (id, role_id, resource, action, attribute_conditions, created_at)
VALUES
  ('__permission_hrbp_user_list__', '__role_hrbp__', 'User', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_hrbp_user_get__', '__role_hrbp__', 'User', 'Get', '{}', CURRENT_TIMESTAMP),
  ('__permission_hrbp_department_list__', '__role_hrbp__', 'Department', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_hrbp_department_get__', '__role_hrbp__', 'Department', 'Get', '{}', CURRENT_TIMESTAMP),
  ('__permission_hrbp_user_department_role_list__', '__role_hrbp__', 'UserDepartmentRole', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_hrbp_department_position_list__', '__role_hrbp__', 'DepartmentPosition', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_hrbp_resume_list__', '__role_hrbp__', 'Resume', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_hrbp_resume_get__', '__role_hrbp__', 'Resume', 'Get', '{}', CURRENT_TIMESTAMP),
  ('__permission_hrbp_resume_create__', '__role_hrbp__', 'Resume', 'Create', '{}', CURRENT_TIMESTAMP),
  ('__permission_hrbp_resume_update__', '__role_hrbp__', 'Resume', 'Update', '{}', CURRENT_TIMESTAMP),
  ('__permission_hrbp_resume_delete__', '__role_hrbp__', 'Resume', 'Delete', '{}', CURRENT_TIMESTAMP),
  ('__permission_hrbp_position_list__', '__role_hrbp__', 'Position', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_hrbp_position_get__', '__role_hrbp__', 'Position', 'Get', '{}', CURRENT_TIMESTAMP),
  ('__permission_hrbp_department_resume_create__', '__role_hrbp__', 'DepartmentResume', 'Create', '{}', CURRENT_TIMESTAMP),
  ('__permission_hrbp_position_resume_create__', '__role_hrbp__', 'PositionResume', 'Create', '{}', CURRENT_TIMESTAMP),
  ('__permission_hrbp_notification_list__', '__role_hrbp__', 'Notification', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_hrbp_notification_get__', '__role_hrbp__', 'Notification', 'Get', '{}', CURRENT_TIMESTAMP),
  ('__permission_hrbp_notification_create__', '__role_hrbp__', 'Notification', 'Create', '{}', CURRENT_TIMESTAMP),
  ('__permission_hrbp_notification_update__', '__role_hrbp__', 'Notification', 'Update', '{}', CURRENT_TIMESTAMP),
  ('__permission_manager_user_list__', '__role_manager__', 'User', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_manager_user_get__', '__role_manager__', 'User', 'Get', '{}', CURRENT_TIMESTAMP),
  ('__permission_manager_department_list__', '__role_manager__', 'Department', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_manager_department_get__', '__role_manager__', 'Department', 'Get', '{}', CURRENT_TIMESTAMP),
  ('__permission_manager_user_department_role_list__', '__role_manager__', 'UserDepartmentRole', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_manager_department_position_list__', '__role_manager__', 'DepartmentPosition', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_manager_resume_list__', '__role_manager__', 'Resume', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_manager_resume_get__', '__role_manager__', 'Resume', 'Get', '{}', CURRENT_TIMESTAMP),
  ('__permission_manager_resume_create__', '__role_manager__', 'Resume', 'Create', '{}', CURRENT_TIMESTAMP),
  ('__permission_manager_position_list__', '__role_manager__', 'Position', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_manager_position_get__', '__role_manager__', 'Position', 'Get', '{}', CURRENT_TIMESTAMP),
  ('__permission_manager_department_resume_create__', '__role_manager__', 'DepartmentResume', 'Create', '{}', CURRENT_TIMESTAMP),
  ('__permission_manager_position_resume_create__', '__role_manager__', 'PositionResume', 'Create', '{}', CURRENT_TIMESTAMP),
  ('__permission_manager_notification_create__', '__role_manager__', 'Notification', 'Create', '{}', CURRENT_TIMESTAMP),
  ('__permission_trainee_user_list__', '__role_trainee__', 'User', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_trainee_user_get__', '__role_trainee__', 'User', 'Get', '{}', CURRENT_TIMESTAMP),
  ('__permission_trainee_department_list__', '__role_trainee__', 'Department', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_trainee_department_get__', '__role_trainee__', 'Department', 'Get', '{}', CURRENT_TIMESTAMP),
  ('__permission_trainee_user_department_role_list__', '__role_trainee__', 'UserDepartmentRole', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_trainee_department_position_list__', '__role_trainee__', 'DepartmentPosition', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_trainee_resume_list__', '__role_trainee__', 'Resume', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_trainee_resume_get__', '__role_trainee__', 'Resume', 'Get', '{}', CURRENT_TIMESTAMP),
  ('__permission_trainee_position_list__', '__role_trainee__', 'Position', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_trainee_position_get__', '__role_trainee__', 'Position', 'Get', '{}', CURRENT_TIMESTAMP),
  ('__permission_trainee_position_resume_create__', '__role_trainee__', 'PositionResume', 'Create', '{}', CURRENT_TIMESTAMP),
  ('__permission_hrd_user_department_role_create__', '__role_hrd__', 'UserDepartmentRole', 'Create', '{}', CURRENT_TIMESTAMP),
  ('__permission_hrd_user_department_role_delete__', '__role_hrd__', 'UserDepartmentRole', 'Delete', '{}', CURRENT_TIMESTAMP),
  ('__permission_hrd_department_resume_create__', '__role_hrd__', 'DepartmentResume', 'Create', '{}', CURRENT_TIMESTAMP),
  ('__permission_social_owner_user_list__', '__role_social_owner__', 'User', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_social_owner_user_get__', '__role_social_owner__', 'User', 'Get', '{}', CURRENT_TIMESTAMP),
  ('__permission_social_owner_department_list__', '__role_social_owner__', 'Department', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_social_owner_department_get__', '__role_social_owner__', 'Department', 'Get', '{}', CURRENT_TIMESTAMP),
  ('__permission_social_owner_user_department_role_list__', '__role_social_owner__', 'UserDepartmentRole', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_social_owner_department_position_list__', '__role_social_owner__', 'DepartmentPosition', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_social_owner_resume_list__', '__role_social_owner__', 'Resume', 'List', '{"chan":["social"]}', CURRENT_TIMESTAMP),
  ('__permission_social_owner_resume_get__', '__role_social_owner__', 'Resume', 'Get', '{"chan":["social"]}', CURRENT_TIMESTAMP),
  ('__permission_social_owner_resume_create__', '__role_social_owner__', 'Resume', 'Create', '{"chan":["social"]}', CURRENT_TIMESTAMP),
  ('__permission_social_owner_resume_update__', '__role_social_owner__', 'Resume', 'Update', '{"chan":["social"]}', CURRENT_TIMESTAMP),
  ('__permission_social_owner_resume_delete__', '__role_social_owner__', 'Resume', 'Delete', '{"chan":["social"]}', CURRENT_TIMESTAMP),
  ('__permission_social_owner_position_list__', '__role_social_owner__', 'Position', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_social_owner_position_get__', '__role_social_owner__', 'Position', 'Get', '{}', CURRENT_TIMESTAMP),
  ('__permission_social_owner_department_resume_create__', '__role_social_owner__', 'DepartmentResume', 'Create', '{}', CURRENT_TIMESTAMP),
  ('__permission_social_owner_position_resume_create__', '__role_social_owner__', 'PositionResume', 'Create', '{}', CURRENT_TIMESTAMP),
  ('__permission_social_owner_notification_list__', '__role_social_owner__', 'Notification', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_social_owner_notification_get__', '__role_social_owner__', 'Notification', 'Get', '{}', CURRENT_TIMESTAMP),
  ('__permission_social_owner_notification_create__', '__role_social_owner__', 'Notification', 'Create', '{}', CURRENT_TIMESTAMP),
  ('__permission_social_owner_notification_update__', '__role_social_owner__', 'Notification', 'Update', '{}', CURRENT_TIMESTAMP),
  ('__permission_campus_owner_user_list__', '__role_campus_owner__', 'User', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_campus_owner_user_get__', '__role_campus_owner__', 'User', 'Get', '{}', CURRENT_TIMESTAMP),
  ('__permission_campus_owner_department_list__', '__role_campus_owner__', 'Department', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_campus_owner_department_get__', '__role_campus_owner__', 'Department', 'Get', '{}', CURRENT_TIMESTAMP),
  ('__permission_campus_owner_user_department_role_list__', '__role_campus_owner__', 'UserDepartmentRole', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_campus_owner_department_position_list__', '__role_campus_owner__', 'DepartmentPosition', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_campus_owner_resume_list__', '__role_campus_owner__', 'Resume', 'List', '{"chan":["campus"]}', CURRENT_TIMESTAMP),
  ('__permission_campus_owner_resume_get__', '__role_campus_owner__', 'Resume', 'Get', '{"chan":["campus"]}', CURRENT_TIMESTAMP),
  ('__permission_campus_owner_resume_create__', '__role_campus_owner__', 'Resume', 'Create', '{"chan":["campus"]}', CURRENT_TIMESTAMP),
  ('__permission_campus_owner_resume_update__', '__role_campus_owner__', 'Resume', 'Update', '{"chan":["campus"]}', CURRENT_TIMESTAMP),
  ('__permission_campus_owner_resume_delete__', '__role_campus_owner__', 'Resume', 'Delete', '{"chan":["campus"]}', CURRENT_TIMESTAMP),
  ('__permission_campus_owner_position_list__', '__role_campus_owner__', 'Position', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_campus_owner_position_get__', '__role_campus_owner__', 'Position', 'Get', '{}', CURRENT_TIMESTAMP),
  ('__permission_campus_owner_department_resume_create__', '__role_campus_owner__', 'DepartmentResume', 'Create', '{}', CURRENT_TIMESTAMP),
  ('__permission_campus_owner_position_resume_create__', '__role_campus_owner__', 'PositionResume', 'Create', '{}', CURRENT_TIMESTAMP),
  ('__permission_campus_owner_notification_list__', '__role_campus_owner__', 'Notification', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_campus_owner_notification_get__', '__role_campus_owner__', 'Notification', 'Get', '{}', CURRENT_TIMESTAMP),
  ('__permission_campus_owner_notification_create__', '__role_campus_owner__', 'Notification', 'Create', '{}', CURRENT_TIMESTAMP),
  ('__permission_campus_owner_notification_update__', '__role_campus_owner__', 'Notification', 'Update', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_user_list__', '__role_super_admin__', 'User', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_user_get__', '__role_super_admin__', 'User', 'Get', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_department_list__', '__role_super_admin__', 'Department', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_department_get__', '__role_super_admin__', 'Department', 'Get', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_position_list__', '__role_super_admin__', 'Position', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_position_get__', '__role_super_admin__', 'Position', 'Get', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_position_create__', '__role_super_admin__', 'Position', 'Create', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_position_update__', '__role_super_admin__', 'Position', 'Update', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_position_delete__', '__role_super_admin__', 'Position', 'Delete', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_resume_list__', '__role_super_admin__', 'Resume', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_resume_get__', '__role_super_admin__', 'Resume', 'Get', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_resume_create__', '__role_super_admin__', 'Resume', 'Create', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_resume_update__', '__role_super_admin__', 'Resume', 'Update', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_resume_delete__', '__role_super_admin__', 'Resume', 'Delete', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_role_list__', '__role_super_admin__', 'Role', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_role_get__', '__role_super_admin__', 'Role', 'Get', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_role_create__', '__role_super_admin__', 'Role', 'Create', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_role_update__', '__role_super_admin__', 'Role', 'Update', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_role_delete__', '__role_super_admin__', 'Role', 'Delete', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_permission_list__', '__role_super_admin__', 'Permission', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_permission_create__', '__role_super_admin__', 'Permission', 'Create', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_permission_delete__', '__role_super_admin__', 'Permission', 'Delete', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_user_department_role_list__', '__role_super_admin__', 'UserDepartmentRole', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_user_department_role_create__', '__role_super_admin__', 'UserDepartmentRole', 'Create', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_user_department_role_delete__', '__role_super_admin__', 'UserDepartmentRole', 'Delete', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_department_position_list__', '__role_super_admin__', 'DepartmentPosition', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_department_position_create__', '__role_super_admin__', 'DepartmentPosition', 'Create', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_department_position_delete__', '__role_super_admin__', 'DepartmentPosition', 'Delete', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_department_resume_list__', '__role_super_admin__', 'DepartmentResume', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_department_resume_create__', '__role_super_admin__', 'DepartmentResume', 'Create', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_department_resume_delete__', '__role_super_admin__', 'DepartmentResume', 'Delete', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_position_resume_list__', '__role_super_admin__', 'PositionResume', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_position_resume_get__', '__role_super_admin__', 'PositionResume', 'Get', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_position_resume_create__', '__role_super_admin__', 'PositionResume', 'Create', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_position_resume_update__', '__role_super_admin__', 'PositionResume', 'Update', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_role_relation_list__', '__role_super_admin__', 'RoleRelation', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_role_relation_create__', '__role_super_admin__', 'RoleRelation', 'Create', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_role_relation_delete__', '__role_super_admin__', 'RoleRelation', 'Delete', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_notification_list__', '__role_super_admin__', 'Notification', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_notification_get__', '__role_super_admin__', 'Notification', 'Get', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_notification_create__', '__role_super_admin__', 'Notification', 'Create', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_notification_update__', '__role_super_admin__', 'Notification', 'Update', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_audit_log_list__', '__role_super_admin__', 'AuditLog', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_job_list__', '__role_super_admin__', 'Job', 'List', '{}', CURRENT_TIMESTAMP),
  ('__permission_super_admin_job_get__', '__role_super_admin__', 'Job', 'Get', '{}', CURRENT_TIMESTAMP)
ON CONFLICT(role_id, resource, action, attribute_conditions) DO NOTHING;

INSERT INTO role_relations (id, parent_role_id, child_role_id, created_at)
VALUES
  ('__role_relation_hrd_hrbp__', '__role_hrd__', '__role_hrbp__', CURRENT_TIMESTAMP),
  ('__role_relation_hrd_manager__', '__role_hrd__', '__role_manager__', CURRENT_TIMESTAMP),
  ('__role_relation_hrd_trainee__', '__role_hrd__', '__role_trainee__', CURRENT_TIMESTAMP),
  ('__role_relation_super_admin_hrd__', '__role_super_admin__', '__role_hrd__', CURRENT_TIMESTAMP),
  ('__role_relation_super_admin_social_owner__', '__role_super_admin__', '__role_social_owner__', CURRENT_TIMESTAMP),
  ('__role_relation_super_admin_campus_owner__', '__role_super_admin__', '__role_campus_owner__', CURRENT_TIMESTAMP)
ON CONFLICT(parent_role_id, child_role_id) DO NOTHING;

-- +goose Down
DELETE FROM role_relations
WHERE parent_role_id IN ('__role_hrd__', '__role_super_admin__');

DELETE FROM permissions
WHERE role_id IN ('__role_hrbp__','__role_hrd__','__role_manager__','__role_trainee__','__role_social_owner__','__role_campus_owner__','__role_super_admin__');

DELETE FROM roles
WHERE id IN ('__role_hrbp__','__role_hrd__','__role_manager__','__role_trainee__','__role_social_owner__','__role_campus_owner__','__role_super_admin__');
